repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        name: mypy (src)
        args:
          - "--ignore-missing-imports"
          - "--exclude=src/llm/router.py"
        files: ^src/.*\.py$

  - repo: local
    hooks:
      - id: run-tests-with-coverage
        name: Run pytest with coverage (pre-push)
        entry: ./scripts/run-tests.sh --cov=src --cov-report=term-missing
        language: system
        pass_filenames: false
        stages: [push]
