name: 'Setup Python Environment'
description: 'Checks out code, sets up Python, caches dependencies, and installs them.'
inputs:
  python-version:
    description: 'The Python version to use.'
    required: true
    default: '3.11'
  install-dev-reqs:
    description: 'Whether to install requirements-dev.txt'
    required: false
    default: 'true'
  install-docs-reqs:
    description: 'Whether to install requirements-docs.txt'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        # Include all requirements files in the cache key
        key: ${{ runner.os }}-pip-${{ inputs.python-version }}-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ inputs.python-version }}-
          ${{ runner.os }}-pip-
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        if [ "${{ inputs.install-dev-reqs }}" == "true" ] && [ -f requirements-dev.txt ]; then
          pip install -r requirements-dev.txt
        fi
        if [ "${{ inputs.install-docs-reqs }}" == "true" ] && [ -f requirements-docs.txt ]; then
          pip install -r requirements-docs.txt
        fi
