permissions:
  contents: read
name: Pylint

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12" ]
    steps:
    - name: Setup Python Environment
      uses: ./.github/actions/setup-python-env
      with:
        python-version: ${{ matrix.python-version }}
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
